### ISSUE TITLE
docs: add GitHub Actions for diff files

### ISSUE THREAD

**Issue by azu** [secretlint/secretlint#166]
We want to add documents that run secretlint only on changed files on Pull Request.

```yaml
name: Secretlint
on: [pull_request]

# secretlint + git diff on Pull Request
# https://github.com/secretlint/secretlint

jobs:
  test:
    name: "Secretlint"
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - uses: technote-space/get-diff-action@v4
      - name: setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install
        run: npm ci
      - name: Lint with Secretlint
        run: npx --no-install secretlint ${{ env.GIT_DIFF_FILTERED }}
        if: env.GIT_DIFF && !env.MATCHED_FILES
```
